### ISSUE TITLE
https://api.icq.net/aim/startOSCARSession returns 404, clientLogin method fails

### ISSUE THREAD

**Issue by peci1** [EionRobb/icyque#40]
I think this has to do with the recent major update of ICQ clients...

**Comment by EionRobb** [comment]
We don't use "startOSCARSession" in the IcyQue plugin.  Sounds like you're using "ICQ" in the protocol dropdown list instead of "ICQ (WIM)"

**Comment by EionRobb** [comment]
Have a look at https://github.com/EionRobb/icyque#setup at how to switch to the right option

**Comment by peci1** [comment]
Ahh, you're right. I'm setting up pidgin via a provisioning script and it apparently failed to install icyque, so I thought I'm using it even though I wasn't... All good, now it works.
