### ISSUE TITLE
MD5-based login doesn't work

### ISSUE THREAD

**Issue by peci1** [EionRobb/icyque#41]
MD5-based login reports that it cannot connect to the authentication server: SSL connection failed.

This currently leaves icyque with no workin login method :(

**Comment by EionRobb** [comment]
We don't do MD5 authentication in the IcyQue plugin.  Looks like you're getting it mixed up for the ICQ protocol that ships with Pidgin.  You should be using "ICQ (WIM)" as per https://github.com/EionRobb/icyque#setup

**Comment by peci1** [comment]
Ahh, you're right. I'm setting up pidgin via a provisioning script and it apparently failed to install icyque, so I thought I'm using it even though I wasn't... All good, now it works.
