### ISSUE TITLE
Requirements information is missing on readme.md

### ISSUE THREAD

**Issue by chris-vo** [EionRobb/icyque#5]
Had a looong search untill I found that information on one of your other projects.
icyque seems to need libjson-glib-1.0.dll installed in folder (C:\Program Files (x86)\Pidgin).
Otherwise ICQ (WIM) is not available in pidgins account settings.

**Comment by EionRobb** [comment]
I am shocked and appalled that you aren't using any of my other plugins ;)

On a more serious note, thanks for pointing that out.  I'll update the docs to try clarify :)

**Comment by NirvaThomish** [comment]
Hello, I've "installed" both of Your dlls... But without success. Pidgin (2.13.0) is able ony to receive messages, but, not to send...
Tested on two PC with W7Pro.

**Comment by EionRobb** [comment]
@NirvaThomish please start a new issue
